org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=128m -XX:+UseG1GC -Xss256k -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.caching=true
org.gradle.daemon.idletimeout=600000
android.useAndroidX=true
android.enableJetifier=false
kotlin.daemon.jvmargs=-Xmx384m
kotlin.incremental=false




